medicine/urls.py
from django.urls import path

from .views.medical_evaluation_views import (MedicalEvaluationListView,
                                             create_medical_evaluation,
                                             deactivate_medical_evaluation,
                                             list_medical_evaluations,
                                             medical_evaluation_detail,
                                             update_medical_evaluation)
from .views.medication_views import (MedicationListView, create_medication,
                                     deactivate_medication, list_medications,
                                     medication_detail, update_medication)
from .views.medicine_views import (MedicineListView, create_medicine,
                                   deactivate_medicine, list_medicines,
                                   medicine_detail, update_medicine)
from .views.nursing_professional_views import (
    NursingProfessionalAutocompleteView, NursingProfessionalListView,
    create_nursing_professional, deactivate_nursing_professional,
    list_nursing_professionals, nursing_professional_detail,
    update_nursing_professional)
from .views.patient_views import (PatientAutocompleteView, PatientListView,
                                  create_patient, deactivate_patient,
                                  list_patients, patient_detail,
                                  update_patient)

app_name = 'medicine'

prefix_medicine_url = 'medicine'
prefix_patient_url = 'patient'
prefix_nursing_professional_url = 'nursing-professional'
prefix_medical_evaluation_url = 'medical-evaluation'
prefix_medication_url = 'medication'

urlpatterns = [
    # Medicine
    path(
        route=f'{prefix_medicine_url}/list/',
        view=list_medicines,
        name='medicine-list'
    ),
    path(
        route=f'{prefix_medicine_url}/detail/<int:pk>/',
        view=medicine_detail,
        name='medicine-detail'
    ),
    path(
        route=f'{prefix_medicine_url}/create/',
        view=create_medicine,
        name='medicine-create'
    ),
    path(
        route=f'{prefix_medicine_url}/update/<int:pk>/',
        view=update_medicine,
        name='medicine-update'
    ),
    path(
        route=f'{prefix_medicine_url}/deactivate/<int:pk>/',
        view=deactivate_medicine,
        name='medicine-deactivate'
    ),
    path(
        route=f'{prefix_medicine_url}/data/',
        view=MedicineListView.as_view(),
        name='medicine-data'
    ),

    # Patient
    path(
        route=f'{prefix_patient_url}/list/',
        view=list_patients,
        name='patient-list'),
    path(
        route=f'{prefix_patient_url}/detail/<int:pk>/',
        view=patient_detail,
        name='patient-detail'),
    path(
        route=f'{prefix_patient_url}/create/',
        view=create_patient,
        name='patient-create'),
    path(
        route=f'{prefix_patient_url}/update/<int:pk>/',
        view=update_patient,
        name='patient-update'),
    path(
        route=f'{prefix_patient_url}/deactivate/<int:pk>/',
        view=deactivate_patient,
        name='patient-deactivate'
    ),
    path(
        route=f'{prefix_patient_url}/data/',
        view=PatientListView.as_view(),
        name='patient-data'
    ),
    path(
        route=f'{prefix_patient_url}/autocomplete/',
        view=PatientAutocompleteView.as_view(),
        name='patient-autocomplete'
    ),

    # Nursing Professional
    path(
        route=f'{prefix_nursing_professional_url}/list/',
        view=list_nursing_professionals,
        name='nursing-professional-list'),
    path(
        route=f'{prefix_nursing_professional_url}/detail/<int:pk>/',
        view=nursing_professional_detail,
        name='nursing-professional-detail'),
    path(
        route=f'{prefix_nursing_professional_url}/create/',
        view=create_nursing_professional,
        name='nursing-professional-create'),
    path(
        route=f'{prefix_nursing_professional_url}/update/<int:pk>/',
        view=update_nursing_professional,
        name='nursing-professional-update'),
    path(
        route=f'{prefix_nursing_professional_url}/deactivate/<int:pk>/',
        view=deactivate_nursing_professional,
        name='nursing-professional-deactivate'
    ),
    path(
        route=f'{prefix_nursing_professional_url}/data/',
        view=NursingProfessionalListView.as_view(),
        name='nursing-professional-data'
    ),
    path(
        route=f'{prefix_nursing_professional_url}/autocomplete/',
        view=NursingProfessionalAutocompleteView.as_view(),
        name='nursing-professional-autocomplete'
    ),

    # Medical Evaluation
    path(
        route=f'{prefix_medical_evaluation_url}/list/',
        view=list_medical_evaluations,
        name='medical-evaluation-list'),
    path(
        route=f'{prefix_medical_evaluation_url}/detail/<int:pk>/',
        view=medical_evaluation_detail,
        name='medical-evaluation-detail'),
    path(
        route=f'{prefix_medical_evaluation_url}/create/',
        view=create_medical_evaluation,
        name='medical-evaluation-create'),
    path(
        route=f'{prefix_medical_evaluation_url}/update/<int:pk>/',
        view=update_medical_evaluation,
        name='medical-evaluation-update'),
    path(
        route=f'{prefix_medical_evaluation_url}/deactivate/<int:pk>/',
        view=deactivate_medical_evaluation,
        name='medical-evaluation-deactivate'
    ),
    path(
        route=f'{prefix_medical_evaluation_url}/data/',
        view=MedicalEvaluationListView.as_view(),
        name='medical-evaluation-data'
    ),

    # Medication
    path(
        route=f'{prefix_medication_url}/list/',
        view=list_medications,
        name='medication-list'),
    path(
        route=f'{prefix_medication_url}/detail/<int:pk>/',
        view=medication_detail,
        name='medication-detail'),
    path(
        route=f'{prefix_medication_url}/create/',
        view=create_medication,
        name='medication-create'),
    path(
        route=f'{prefix_medication_url}/update/<int:pk>/',
        view=update_medication,
        name='medication-update'),
    path(
        route=f'{prefix_medication_url}/deactivate/<int:pk>/',
        view=deactivate_medication,
        name='medication-deactivate'
    ),
    path(
        route=f'{prefix_medication_url}/data/',
        view=MedicationListView.as_view(),
        name='medication-data'
    ),
]

senioren/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog
from medicine.views.index_views import index
from user.views import login, logout

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),

    path('', index, name='index'),

    path('admin/', admin.site.urls, name='admin'),

    path('medicines/', include('medicine.urls', namespace='medicine')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

medicine/forms/medical_evaluation_forms.py
from dal import autocomplete
from django import forms
from tempus_dominus.widgets import DateTimePicker

from ..models import MedicalEvaluation
from ..services.nursing_professional_service import \
    get_all_nursing_professionals
from ..services.patient_service import get_all_patients


class MedicalEvaluationForm(forms.ModelForm):
    """MedicalEvaluation form."""

    schedule = forms.DateTimeField(
        label=MedicalEvaluation._meta.get_field('schedule').verbose_name,
        input_formats=['%d-%m-%Y %H:%M:%S'],
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        )
    )

    patient = forms.ModelChoiceField(
        label=MedicalEvaluation._meta.get_field('patient').verbose_name,
        queryset=get_all_patients(),
        widget=autocomplete.ModelSelect2(url='medicine:patient-autocomplete')
    )

    nursing_professional = forms.ModelChoiceField(
        label=MedicalEvaluation._meta.get_field(
            'nursing_professional'
        ).verbose_name,
        queryset=get_all_nursing_professionals(),
        widget=autocomplete.ModelSelect2(
            url='medicine:nursing-professional-autocomplete')
    )

    class Meta:
        model = MedicalEvaluation
        fields = [
            'schedule',
            'heart_pressure',
            'glucose',
            'observation',
            'patient',
            'nursing_professional',
        ]

medicine/forms/medicine_forms.py
from django import forms

from ..models import Medicine


class MedicineForm(forms.ModelForm):
    """Medicine form."""
    expiration_date = forms.DateField(
        label=Medicine._meta.get_field('expiration_date').verbose_name,
        localize=True,
        widget=forms.DateInput(
            format='%d/%m/%Y',
            attrs={
                'type': 'date'
            }
        )
    )

    class Meta:
        model = Medicine
        fields = [
            'name',
            'description',
            'batch',
            'expiration_date',
            'stock_qty',
        ]

medicine/views/index_views.py
"""Index views"""

import datetime

from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render
from medicine.models import MedicalEvaluation, Medication
from medicine.services import medication_service


def _get_amount_created_today(model: Medication | MedicalEvaluation) -> int:
    return model.active_manager.filter(
        created_at__startswith=datetime.date.today()

    ).count()


def _get_amount_created_week(model: Medication | MedicalEvaluation) -> int:
    return model.active_manager.filter(
        created_at__lte=datetime.datetime.now(),
        created_at__gte=F('created_at') - datetime.timedelta(7),
    ).count()


@login_required()
def index(request: WSGIRequest) -> HttpResponse:
    """
    Dashboard Page.

    Shows some abstracts about Medication and Medical Evaluation.
    """
    medications_today = _get_amount_created_today(Medication)
    medications_this_week = _get_amount_created_week(Medication)

    medical_evaluations_today = _get_amount_created_today(MedicalEvaluation)
    medical_evaluations_this_week = _get_amount_created_week(MedicalEvaluation)

    medications = medication_service.get_all_medications()

    context = {
        'medications_today': medications_today,
        'medications_this_week': medications_this_week,
        'medical_evaluations_today': medical_evaluations_today,
        'medical_evaluations_this_week': medical_evaluations_this_week,

        'model': Medication,
        'medications': medications
    }

    return render(
        request=request,
        template_name='index.html',
        context=context
    )

medicine/views/medical_evaluation_views.py
from typing import Tuple

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django_serverside_datatable.views import ServerSideDatatableView
from medicine.entities import medical_evaluation
from medicine.forms.medical_evaluation_forms import MedicalEvaluationForm
from medicine.models import MedicalEvaluation
from medicine.services import medical_evaluation_service


def get_cleaned_data(form: MedicalEvaluationForm) -> Tuple:
    schedule = form.cleaned_data['schedule']
    heart_pressure = form.cleaned_data['heart_pressure']
    glucose = form.cleaned_data['glucose']
    observation = form.cleaned_data['observation']
    patient = form.cleaned_data['patient']
    nursing_professional = form.cleaned_data['nursing_professional']

    return (
        schedule,
        heart_pressure,
        glucose,
        observation,
        patient,
        nursing_professional,
    )


@login_required()
def list_medical_evaluations(request: WSGIRequest) -> HttpResponse:
    medical_evaluations = medical_evaluation_service.list_medical_evaluations()
    context = {
        'model': MedicalEvaluation,
        'medical_evaluations': medical_evaluations
    }

    return render(
        request=request,
        template_name='templates/medical_evaluation/list_medical_evaluations.html',
        context=context
    )


@login_required()
def medical_evaluation_detail(request: WSGIRequest, pk: int) -> HttpResponse:
    found_medical_evaluation = medical_evaluation_service.get_medical_evaluation_by_id(
        pk)
    context = {
        'medical_evaluation': found_medical_evaluation,
    }

    return render(
        request=request,
        template_name='templates/medical_evaluation/medical_evaluation_detail.html',
        context=context
    )


@login_required()
def create_medical_evaluation(request: WSGIRequest) -> HttpResponse:
    if request.method == 'POST':
        form = MedicalEvaluationForm(request.POST)
        if form.is_valid():
            (
                schedule,
                heart_pressure,
                glucose,
                observation,
                patient,
                nursing_professional,
            ) = get_cleaned_data(form)

            new_medical_evaluation = medical_evaluation.MedicalEvaluation(
                schedule=schedule,
                heart_pressure=heart_pressure,
                glucose=glucose,
                observation=observation,
                patient=patient,
                nursing_professional=nursing_professional,
                created_at=None,
                updated_at=None,
                created_by=request.user,
                updated_by=None,
                is_active=True,
                deactivated_by=None,
            )
            medical_evaluation_service.create_medical_evaluation(
                new_medical_evaluation
            )

            return redirect('medicine:medical-evaluation-list')
    else:
        form = MedicalEvaluationForm()
    context = {
        'form': form,
        'is_edit': False,
    }

    return render(
        request=request,
        template_name='templates/medical_evaluation/form_medical_evaluation.html',
        context=context
    )


@login_required()
def update_medical_evaluation(request: WSGIRequest, pk: int) -> HttpResponse:
    old_medical_evaluation = medical_evaluation_service.get_medical_evaluation_by_id(
        pk
    )
    form = MedicalEvaluationForm(
        request.POST or None, instance=old_medical_evaluation
    )
    if request.method == 'POST':
        if form.is_valid():
            (
                schedule,
                heart_pressure,
                glucose,
                observation,
                patient,
                nursing_professional,
            ) = get_cleaned_data(form)

            new_medical_evaluation = medical_evaluation.MedicalEvaluation(
                schedule=schedule,
                heart_pressure=heart_pressure,
                glucose=glucose,
                observation=observation,
                patient=patient,
                nursing_professional=nursing_professional,
                created_at=old_medical_evaluation.created_at,
                updated_at=None,
                created_by=old_medical_evaluation.created_by,
                updated_by=request.user,
                is_active=old_medical_evaluation.is_active,
                deactivated_by=old_medical_evaluation.deactivated_by,
            )
            medical_evaluation_service.update_medical_evaluation(
                old_medical_evaluation, new_medical_evaluation)

            return redirect('medicine:medical-evaluation-list')

    context = {
        'form': form,
        'is_edit': True,
    }

    return render(
        request=request,
        template_name='templates/medical_evaluation/form_medical_evaluation.html',
        context=context
    )


@login_required()
def deactivate_medical_evaluation(request: WSGIRequest, pk: int) -> HttpResponse:
    found_medical_evaluation = medical_evaluation_service.get_medical_evaluation_by_id(
        pk
    )
    if request.method == 'POST':
        user = request.user
        found_medical_evaluation.updated_by = user
        medical_evaluation_service.deactivate_medical_evaluation(
            found_medical_evaluation, user)

        return redirect('medicine:medical-evaluation-list')

    context = {
        'medical_evaluation': found_medical_evaluation,
    }

    return render(
        request=request,
        template_name="templates/medical_evaluation/deactivate_medical_evaluation.html",
        context=context
    )


class MedicalEvaluationListView(LoginRequiredMixin, ServerSideDatatableView):
    queryset = medical_evaluation_service.get_all_medical_evaluations()
    model = MedicalEvaluation
    columns = [
        'id',
        'schedule',
        'heart_pressure',
        'glucose',
        'observation',
        'patient__name',
        'nursing_professional__name',
    ]

medicine/views/utils.py
import re

from django.core.handlers.wsgi import WSGIRequest
from django.http import QueryDict


def clean_mask_cpf(cpf: str) -> str:
    return re.sub(r'\D', '', cpf)


def mask_cpf(cpf: str) -> str:
    if len(cpf) == 11:
        return f'{cpf[:3]}.{cpf[3:6]}.{cpf[6:9]}-{cpf[9:]}'
    return cpf


def clean_masked_inputs_form(request: WSGIRequest) -> QueryDict:
    if request.method == 'POST':
        data = request.POST.copy()
    else:
        data = request.GET.copy()

    if 'cpf' in data:
        data['cpf'] = clean_mask_cpf(data.get('cpf'))

    return data

medicine/templates/nursing_professional/deactivate_nursing_professional.html
{% extends "base.html" %}
{% load custom_tags %}

{% block title %}
    Inativar Profissional de Enfermagem
{% endblock title %}

{% block content_title %}
    Inativar Profissional de Enfermagem
{% endblock content_title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    Código:
                </span>
                    {{ nursing_professional.id }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'name' }}:
                </span>
                    {{ nursing_professional.name }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'coren' }}:
                </span>
                    {{ nursing_professional.coren }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'created_by' }}:
                </span>
                    {{ nursing_professional.created_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'created_at' }}:
                </span>
                    {{ nursing_professional.created_at|date:"d/m/Y" }} {{ nursing_professional.created_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'updated_by' }}:
                </span>
                    {{ nursing_professional.updated_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'updated_at' }}:
                </span>
                    {{ nursing_professional.updated_at|date:"d/m/Y" }} {{ nursing_professional.updated_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'is_active' }}:
                </span>
                    {% if nursing_professional.is_active %}
                        {% include 'utils/icons/icon_check_circle.html' %}
                    {% else %}
                        {% include 'utils/icons/icon_times_circle.html' %}
                    {% endif %}
                </h5>
            </div>
        </div>
    </div>
    <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="my-4 text-center">
            <ul class="list-inline m-0">
                <li class="list-inline-item">
                    <a href="{% url 'medicine:nursing-professional-list' %}">
                        {% include 'utils/forms/form_cancel_btn.html' %}
                    </a>
                </li>
                {% include 'utils/forms/form_deactivate_btn.html' %}
            </ul>
        </div>
    </form>
{% endblock content %}

medicine/templates/nursing_professional/form_nursing_professional.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static %}
{% block title %}
    Cadastrar Profissional de Enfermagem
{% endblock title %}

{% block content_title %}
    {% if is_edit %}Editar{% else %}Cadastrar{% endif %} Profissional de Enfermagem
{% endblock content_title %}

{% block content %}
    <form method="post" autocomplete="off" id="form-crud"
          class="d-flex flex-column justify-content-center align-items-center box-shadow-whisper rounded rounded-3 mb-4">
        {% csrf_token %}
        <div class="form-group col-md-10 col-lg-8 col-xl-6 pt-4">
            <label class="control-label {% if form.name.field.required %}font-weight-bold{% endif %}"
                   for="{{ form.name.id_for_label }}">
                {{ form.name.label }} {% if form.name.field.required %}<span>*</span> {% endif %}
            </label>
            {% if form.name.errors %}
                {{ form.name | add_class:'form-control is-invalid' }}
                <small class="text-danger">{{ form.name.errors|striptags }}</small>
            {% else %}
                {{ form.name | add_class:'form-control' }}
            {% endif %}
        </div>
        <div class="form-group col-md-10 col-lg-8 col-xl-6 pt-4">
            <label class="control-label {% if form.coren.field.required %}font-weight-bold{% endif %}"
                   for="{{ form.coren.id_for_label }}">
                {{ form.coren.label }} {% if form.coren.field.required %}<span>*</span> {% endif %}
            </label>
            {% if form.coren.errors %}
                {{ form.coren | add_class:'form-control is-invalid' }}
                <small class="text-danger">{{ form.coren.errors|striptags }}</small>
            {% else %}
                {{ form.coren | add_class:'form-control' }}
            {% endif %}
        </div>

        <div class="my-4 text-center">
            <ul class="list-inline m-0">
                <li class="list-inline-item">
                    <a href="{% url 'medicine:nursing-professional-list' %}">
                        {% include 'utils/forms/form_cancel_btn.html' %}
                    </a>
                </li>
                {% include 'utils/forms/form_save_btn.html' %}
            </ul>
        </div>
    </form>
{% endblock content %}

medicine/templates/nursing_professional/list_nursing_professionals.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static %}

{% block title %}
    Cadastrar Profissional de Enfermagem
{% endblock title %}

{% block content_title %}
    Cadastrar Profissional de Enfermagem
{% endblock content_title %}

{% block content %}
    <div class="my-4">
        <a class="btn btn-small btn-primary" href="{% url 'medicine:nursing-professional-create' %}">
            Cadastrar
        </a>
    </div>

    <table id="gridNursingProfessional" class="table table-striped table-bordered" style="width: 100%">
        <thead>
        <tr>
            <th>{{ model|get_verbose_name:'name' }}</th>
            <th>{{ model|get_verbose_name:'coren' }}</th>
            {% include 'utils/tables/thead_actions.html' %}
        </tr>
        </thead>

        <tbody>
        </tbody>
    </table>
{% endblock content %}

{% block custom_script %}
    <!-- Datatable initialization -->
    <script src="{% static 'js/grid-datatables.js' %}"></script>
{% endblock custom_script %}

medicine/templates/nursing_professional/nursing_professional_detail.html
{% extends "base.html" %}
{% load custom_tags %}

{% block title %}
    Visualizar Profissional de Enfermagem
{% endblock title %}

{% block content_title %}
    Visualizar Profissional de Enfermagem
{% endblock content_title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    Código:
                </span>
                    {{ nursing_professional.id }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'name' }}:
                </span>
                    {{ nursing_professional.name }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'coren' }}:
                </span>
                    {{ nursing_professional.coren }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'created_by' }}:
                </span>
                    {{ nursing_professional.created_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'created_at' }}:
                </span>
                    {{ nursing_professional.created_at|date:"d/m/Y" }} {{ nursing_professional.created_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'updated_by' }}:
                </span>
                    {{ nursing_professional.updated_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'updated_at' }}:
                </span>
                    {{ nursing_professional.updated_at|date:"d/m/Y" }} {{ nursing_professional.updated_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ nursing_professional|get_verbose_name:'is_active' }}:
                </span>
                    {% if nursing_professional.is_active %}
                        {% include 'utils/icons/icon_check_circle.html' %}
                    {% else %}
                        {% include 'utils/icons/icon_times_circle.html' %}
                    {% endif %}
                </h5>
            </div>
        </div>
    </div>
    <div class="my-4 text-center">
        <a href="{% url 'medicine:nursing-professional-list' %}">
            {% include 'utils/forms/form_back_btn.html' %}
        </a>
    </div>
{% endblock content %}