medicine/urls.py
from django.urls import path

from .views.medical_evaluation_views import (MedicalEvaluationListView,
                                             create_medical_evaluation,
                                             deactivate_medical_evaluation,
                                             list_medical_evaluations,
                                             medical_evaluation_detail,
                                             update_medical_evaluation)
from .views.medication_views import (MedicationListView, create_medication,
                                     deactivate_medication, list_medications,
                                     medication_detail, update_medication)
from .views.medicine_views import (MedicineListView, create_medicine,
                                   deactivate_medicine, list_medicines,
                                   medicine_detail, update_medicine)
from .views.nursing_professional_views import (
    NursingProfessionalAutocompleteView, NursingProfessionalListView,
    create_nursing_professional, deactivate_nursing_professional,
    list_nursing_professionals, nursing_professional_detail,
    update_nursing_professional)
from .views.patient_views import (PatientAutocompleteView, PatientListView,
                                  create_patient, deactivate_patient,
                                  list_patients, patient_detail,
                                  update_patient)

app_name = 'medicine'

prefix_medicine_url = 'medicine'
prefix_patient_url = 'patient'
prefix_nursing_professional_url = 'nursing-professional'
prefix_medical_evaluation_url = 'medical-evaluation'
prefix_medication_url = 'medication'

urlpatterns = [
    # Medicine
    path(
        route=f'{prefix_medicine_url}/list/',
        view=list_medicines,
        name='medicine-list'
    ),
    path(
        route=f'{prefix_medicine_url}/detail/<int:pk>/',
        view=medicine_detail,
        name='medicine-detail'
    ),
    path(
        route=f'{prefix_medicine_url}/create/',
        view=create_medicine,
        name='medicine-create'
    ),
    path(
        route=f'{prefix_medicine_url}/update/<int:pk>/',
        view=update_medicine,
        name='medicine-update'
    ),
    path(
        route=f'{prefix_medicine_url}/deactivate/<int:pk>/',
        view=deactivate_medicine,
        name='medicine-deactivate'
    ),
    path(
        route=f'{prefix_medicine_url}/data/',
        view=MedicineListView.as_view(),
        name='medicine-data'
    ),

    # Patient
    path(
        route=f'{prefix_patient_url}/list/',
        view=list_patients,
        name='patient-list'),
    path(
        route=f'{prefix_patient_url}/detail/<int:pk>/',
        view=patient_detail,
        name='patient-detail'),
    path(
        route=f'{prefix_patient_url}/create/',
        view=create_patient,
        name='patient-create'),
    path(
        route=f'{prefix_patient_url}/update/<int:pk>/',
        view=update_patient,
        name='patient-update'),
    path(
        route=f'{prefix_patient_url}/deactivate/<int:pk>/',
        view=deactivate_patient,
        name='patient-deactivate'
    ),
    path(
        route=f'{prefix_patient_url}/data/',
        view=PatientListView.as_view(),
        name='patient-data'
    ),
    path(
        route=f'{prefix_patient_url}/autocomplete/',
        view=PatientAutocompleteView.as_view(),
        name='patient-autocomplete'
    ),

    # Nursing Professional
    path(
        route=f'{prefix_nursing_professional_url}/list/',
        view=list_nursing_professionals,
        name='nursing-professional-list'),
    path(
        route=f'{prefix_nursing_professional_url}/detail/<int:pk>/',
        view=nursing_professional_detail,
        name='nursing-professional-detail'),
    path(
        route=f'{prefix_nursing_professional_url}/create/',
        view=create_nursing_professional,
        name='nursing-professional-create'),
    path(
        route=f'{prefix_nursing_professional_url}/update/<int:pk>/',
        view=update_nursing_professional,
        name='nursing-professional-update'),
    path(
        route=f'{prefix_nursing_professional_url}/deactivate/<int:pk>/',
        view=deactivate_nursing_professional,
        name='nursing-professional-deactivate'
    ),
    path(
        route=f'{prefix_nursing_professional_url}/data/',
        view=NursingProfessionalListView.as_view(),
        name='nursing-professional-data'
    ),
    path(
        route=f'{prefix_nursing_professional_url}/autocomplete/',
        view=NursingProfessionalAutocompleteView.as_view(),
        name='nursing-professional-autocomplete'
    ),

    # Medical Evaluation
    path(
        route=f'{prefix_medical_evaluation_url}/list/',
        view=list_medical_evaluations,
        name='medical-evaluation-list'),
    path(
        route=f'{prefix_medical_evaluation_url}/detail/<int:pk>/',
        view=medical_evaluation_detail,
        name='medical-evaluation-detail'),
    path(
        route=f'{prefix_medical_evaluation_url}/create/',
        view=create_medical_evaluation,
        name='medical-evaluation-create'),
    path(
        route=f'{prefix_medical_evaluation_url}/update/<int:pk>/',
        view=update_medical_evaluation,
        name='medical-evaluation-update'),
    path(
        route=f'{prefix_medical_evaluation_url}/deactivate/<int:pk>/',
        view=deactivate_medical_evaluation,
        name='medical-evaluation-deactivate'
    ),
    path(
        route=f'{prefix_medical_evaluation_url}/data/',
        view=MedicalEvaluationListView.as_view(),
        name='medical-evaluation-data'
    ),

    # Medication
    path(
        route=f'{prefix_medication_url}/list/',
        view=list_medications,
        name='medication-list'),
    path(
        route=f'{prefix_medication_url}/detail/<int:pk>/',
        view=medication_detail,
        name='medication-detail'),
    path(
        route=f'{prefix_medication_url}/create/',
        view=create_medication,
        name='medication-create'),
    path(
        route=f'{prefix_medication_url}/update/<int:pk>/',
        view=update_medication,
        name='medication-update'),
    path(
        route=f'{prefix_medication_url}/deactivate/<int:pk>/',
        view=deactivate_medication,
        name='medication-deactivate'
    ),
    path(
        route=f'{prefix_medication_url}/data/',
        view=MedicationListView.as_view(),
        name='medication-data'
    ),
]

senioren/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog
from medicine.views.index_views import index
from user.views import login, logout

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),

    path('', index, name='index'),

    path('admin/', admin.site.urls, name='admin'),

    path('medicines/', include('medicine.urls', namespace='medicine')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

medicine/models.py
from django.db import models
from django.utils import timezone
from user.models import CustomUser

from medicine.managers import ActiveManager

MARITAL_STATUS_MARRIED_CHOICE = (1, 'Casado(a)')
MARITAL_STATUS_WIDOWED_CHOICE = (2, 'Viúvo(a)')
MARITAL_STATUS_SEPARATED_CHOICE = (3, 'Separado(a)')
MARITAL_STATUS_DIVORCED_CHOICE = (4, 'Divorciado(a)')
MARITAL_STATUS_SINGLE_CHOICE = (5, 'Solteiro(a)')
MARITAL_STATUS_CHOICES = (
    MARITAL_STATUS_MARRIED_CHOICE,
    MARITAL_STATUS_WIDOWED_CHOICE,
    MARITAL_STATUS_SEPARATED_CHOICE,
    MARITAL_STATUS_DIVORCED_CHOICE,
    MARITAL_STATUS_SINGLE_CHOICE,
)

GENDER_MALE_CHOICE = ('M', 'Masculino')
GENDER_FEMALE_CHOICE = ('F', 'Feminino')
GENDER_OTHER_CHOICE = ('', '')
GENDER_CHOICES = (
    GENDER_OTHER_CHOICE,
    GENDER_MALE_CHOICE,
    GENDER_FEMALE_CHOICE,
)


class BaseModel(models.Model):
    """Define common fields used by other Models by inheritance"""

    created_at = models.DateTimeField(
        verbose_name='Criado em',
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        verbose_name='Atualizado em',
        auto_now=True
    )

    created_by = models.ForeignKey(
        CustomUser,
        verbose_name='Criado por',
        related_name='%(app_label)s_%(class)s_related_created_by',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    updated_by = models.ForeignKey(
        CustomUser,
        verbose_name='Atualizado por',
        related_name='%(app_label)s_%(class)s_related_updated_by',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    is_active = models.BooleanField(
        verbose_name='Ativo',
        default=True
    )

    deactivated_by = models.ForeignKey(
        CustomUser,
        verbose_name='Inativado por',
        related_name='%(app_label)s_%(class)s_related_deactivated_by',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    class Meta:
        """Metadata options"""
        abstract = True


class HistoryBaseModel(models.Model):
    """Define common fields used by other History Models by inheritance"""

    created_at = models.DateTimeField(
        verbose_name='Criado em',
        null=False,
        blank=False,
    )

    updated_at = models.DateTimeField(
        verbose_name='Atualizado em',
        null=True,
        blank=True,
    )

    created_by = models.ForeignKey(
        CustomUser,
        verbose_name='Criado por',
        on_delete=models.CASCADE,
        related_name='%(app_label)s_%(class)s_related_created_by',
        null=True,
        blank=True,
    )

    updated_by = models.ForeignKey(
        CustomUser,
        verbose_name='Atualizado por',
        on_delete=models.CASCADE,
        related_name='%(app_label)s_%(class)s_related_updated_by',
        null=True,
        blank=True,
    )

    is_active = models.BooleanField(
        verbose_name='Ativo',
        null=True,
        blank=True,
        default=True,
    )

    deactivated_by = models.ForeignKey(
        CustomUser,
        verbose_name='Inativado por',
        related_name='%(app_label)s_%(class)s_related_deactivated_by',
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )

    class Meta:
        """Metadata options"""
        abstract = True


"""
----- Models -----
"""


class Medicine(BaseModel):
    """Medicine Model"""

    name = models.CharField(
        verbose_name='Nome',
        max_length=80,
        null=False,
        blank=False
    )

    description = models.CharField(
        verbose_name='Descrição',
        max_length=100,
        null=False,
        blank=True
    )

    batch = models.CharField(
        verbose_name='Lote',
        max_length=20,
        null=False,
        blank=True
    )

    expiration_date = models.DateField(
        verbose_name='Data de vencimento',
        null=False,
        blank=False
    )

    stock_qty = models.IntegerField(
        verbose_name='Quantidade em estoque',
        null=False,
        blank=False,
        default=0
    )

    objects = models.Manager()
    active_manager = ActiveManager()

    class Meta:
        """Metadata options"""
        verbose_name = 'Medicamento'
        verbose_name_plural = 'Medicamentos'
        ordering = ('-is_active', 'name',)

    def __str__(self):  # pylint: disable=invalid-str-returned
        return self.name


class Patient(BaseModel):
    """Patient Model"""

    name = models.CharField(
        verbose_name='Nome',
        max_length=80,
        null=False,
        blank=False
    )

    social_name = models.CharField(
        verbose_name='Nome Social',
        max_length=80,
        null=False,
        blank=True
    )

    cpf = models.CharField(
        verbose_name='CPF',
        max_length=11,
        null=False,
        blank=False
    )

    rg = models.CharField(
        verbose_name='RG',
        max_length=20,
        null=False,
        blank=False
    )

    birth_date = models.DateField(
        verbose_name='Data de Nascimento',
        null=False,
        blank=False
    )

    marital_status = models.IntegerField(
        verbose_name='Estado Civil',
        choices=MARITAL_STATUS_CHOICES,
        null=False,
        blank=False
    )

    place_of_birth = models.CharField(
        verbose_name='Naturalidade',
        max_length=80,
        null=False,
        blank=True
    )

    gender = models.CharField(
        max_length=2,
        verbose_name='Sexo',
        choices=GENDER_CHOICES,
        null=False,
        blank=True
    )

    phone = models.CharField(
        verbose_name='Telefone',
        max_length=20,
        null=False,
        blank=True
    )

    observation = models.CharField(
        verbose_name='Observação',
        max_length=200,
        null=False,
        blank=True
    )

    objects = models.Manager()
    active_manager = ActiveManager()

    class Meta:
        """Metadata options"""
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering = ('-is_active', 'name',)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f'Pacient(name={self.name})'


class NursingProfessional(BaseModel):
    """NursingProfessional Model"""

    name = models.CharField(
        verbose_name='Nome',
        max_length=80,
        null=False,
        blank=False
    )
    coren = models.CharField(
        verbose_name='COREN',
        max_length=20,
        null=False,
        blank=False
    )

    objects = models.Manager()
    active_manager = ActiveManager()

    class Meta:
        """Metadata options"""
        verbose_name = 'Profissional de Enfermagem'
        verbose_name_plural = 'Profissionais de Enfermagem'
        ordering = ('-is_active', 'name',)

    def __str__(self):
        return f'{self.name}'

    def __repr__(self):
        return f'NursingProfessional(name={self.name})'


class MedicalEvaluation(BaseModel):
    """MedicalEvaluation Model"""

    schedule = models.DateTimeField(
        verbose_name='Horário',
        null=False,
        blank=False,
        default=timezone.now
    )

    heart_pressure = models.CharField(
        verbose_name='Pressão Arterial',
        max_length=20,
        null=False,
        blank=False
    )

    glucose = models.CharField(
        verbose_name='Glicose',
        max_length=20,
        null=False,
        blank=False
    )

    observation = models.CharField(
        verbose_name='Observação',
        max_length=200,
        null=False,
        blank=True
    )

    patient = models.ForeignKey(
        verbose_name='Paciente',
        to=Patient,
        on_delete=models.CASCADE,
    )

    nursing_professional = models.ForeignKey(
        verbose_name='Profissional de Enfermagem',
        to=NursingProfessional,
        on_delete=models.CASCADE,
    )

    objects = models.Manager()
    active_manager = ActiveManager()

    class Meta:
        """Metadata options"""
        verbose_name = 'Avaliação Médica'
        verbose_name_plural = 'Avaliações Médicas'
        ordering = ('-is_active', '-schedule',)

    def __str__(self):
        return str(self.schedule)


class Medication(BaseModel):
    """Metadata options"""

    schedule = models.DateTimeField(
        verbose_name='Horário',
        null=False,
        blank=False,
        default=timezone.now
    )

    observation = models.CharField(
        verbose_name='Observação',
        max_length=200,
        null=False,
        blank=True
    )

    medicines = models.ManyToManyField(
        Medicine,
        verbose_name='Medicamentos'
    )

    patient = models.ForeignKey(
        Patient,
        verbose_name='Paciente',
        on_delete=models.CASCADE
    )

    nursing_professional = models.ForeignKey(
        NursingProfessional,
        verbose_name='Profissional de Enfermagem',
        on_delete=models.CASCADE
    )

    objects = models.Manager()
    active_manager = ActiveManager()

    class Meta:
        """Metadata options"""
        verbose_name = 'Medicação'
        verbose_name_plural = 'Medicações'
        ordering = ('-is_active', '-schedule',)

    def __str__(self):
        return str(self.schedule)


"""
----- History Models -----
"""


class MedicineHistory(HistoryBaseModel):
    """Medicine History Model"""

    name = models.CharField(
        verbose_name='Nome',
        max_length=80,
        null=True,
        blank=True
    )

    description = models.CharField(
        verbose_name='Descrição',
        max_length=100,
        null=True,
        blank=True
    )

    batch = models.CharField(
        verbose_name='Lote',
        max_length=20,
        null=True,
        blank=True
    )

    expiration_date = models.DateField(
        verbose_name='Data de vencimento',
        null=True,
        blank=True
    )

    stock_qty = models.IntegerField(
        verbose_name='Quantidade em estoque',
        null=True,
        blank=True,

medicine/forms/nursing_professional_forms.py
from django import forms

from ..models import NursingProfessional


class NursingProfessionalForm(forms.ModelForm):
    """NursingProfessional form."""

    class Meta:
        model = NursingProfessional
        fields = [
            'name',
            'coren',
        ]

medicine/views/utils.py
import re

from django.core.handlers.wsgi import WSGIRequest
from django.http import QueryDict


def clean_mask_cpf(cpf: str) -> str:
    return re.sub(r'\D', '', cpf)


def mask_cpf(cpf: str) -> str:
    if len(cpf) == 11:
        return f'{cpf[:3]}.{cpf[3:6]}.{cpf[6:9]}-{cpf[9:]}'
    return cpf


def clean_masked_inputs_form(request: WSGIRequest) -> QueryDict:
    if request.method == 'POST':
        data = request.POST.copy()
    else:
        data = request.GET.copy()

    if 'cpf' in data:
        data['cpf'] = clean_mask_cpf(data.get('cpf'))

    return data

medicine/templates/patient/deactivate_patient.html
{% extends "base.html" %}
{% load custom_tags %}

{% block title %}
    Inativar Paciente
{% endblock title %}

{% block content_title %}
    Inativar Paciente
{% endblock content_title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    Código:
                </span>
                    {{ patient.id }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'name' }}:
                </span>
                    {{ patient.name }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'social_name' }}:
                </span>
                    {{ patient.social_name }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'cpf' }}:
                </span>
                    {{ patient.cpf }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'rg' }}:
                </span>
                    {{ patient.rg }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'birth_date' }}:
                </span>
                    {{ patient.birth_date }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'marital_status' }}:
                </span>
                    {{ patient.marital_status }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'place_of_birth' }}:
                </span>
                    {{ patient.place_of_birth }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'gender' }}:
                </span>
                    {{ patient.gender }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'phone' }}:
                </span>
                    {{ patient.phone }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'observation' }}:
                </span>
                    {{ patient.observation }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'created_by' }}:
                </span>
                    {{ patient.created_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'created_at' }}:
                </span>
                    {{ patient.created_at|date:"d/m/Y" }} {{ patient.created_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'updated_by' }}:
                </span>
                    {{ patient.updated_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'updated_at' }}:
                </span>
                    {{ patient.updated_at|date:"d/m/Y" }} {{ patient.updated_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'is_active' }}:
                </span>
                    {% if patient.is_active %}
                        {% include 'utils/icons/icon_check_circle.html' %}
                    {% else %}
                        {% include 'utils/icons/icon_times_circle.html' %}
                    {% endif %}
                </h5>
            </div>
        </div>
    </div>
    <form method="post" autocomplete="off">
        {% csrf_token %}
        <div class="my-4 text-center">
            <ul class="list-inline m-0">
                <li class="list-inline-item">
                    <a href="{% url 'medicine:patient-list' %}">
                        {% include 'utils/forms/form_cancel_btn.html' %}
                    </a>
                </li>
                {% include 'utils/forms/form_deactivate_btn.html' %}
            </ul>
        </div>
    </form>
{% endblock content %}

medicine/templates/patient/list_patients.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static %}

{% block title %}
    Cadastrar Paciente
{% endblock title %}

{% block content_title %}
    Cadastrar Paciente
{% endblock content_title %}

{% block content %}
    <div class="my-4">
        <a class="btn btn-small btn-primary" href="{% url 'medicine:patient-create' %}">Cadastrar</a>
    </div>

    <table id="gridPatient" class="table table-striped table-bordered" style="width: 100%">
        <thead>
        <tr>
            <th>{{ model|get_verbose_name:'name' }}</th>
            <th>{{ model|get_verbose_name:'cpf' }}</th>
            <th>{{ model|get_verbose_name:'birth_date' }}</th>
            <th>{{ model|get_verbose_name:'phone' }}</th>
            {% include 'utils/tables/thead_actions.html' %}
        </tr>
        </thead>

        <tbody>
        </tbody>
    </table>
{% endblock content %}

{% block custom_script %}
    <!-- Datatable initialization -->
    <script src="{% static 'js/grid-datatables.js' %}"></script>
{% endblock custom_script %}

medicine/templates/patient/patient_detail.html
{% extends "base.html" %}
{% load custom_tags %}

{% block title %}
    Visualizar Paciente
{% endblock title %}

{% block content_title %}
    Visualizar Paciente
{% endblock content_title %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    Código:
                </span>
                    {{ patient.id }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'name' }}:
                </span>
                    {{ patient.name }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'social_name' }}:
                </span>
                    {{ patient.social_name }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'cpf' }}:
                </span>
                    {{ patient.cpf }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'rg' }}:
                </span>
                    {{ patient.rg }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'birth_date' }}:
                </span>
                    {{ patient.birth_date }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'marital_status' }}:
                </span>
                    {{ patient.get_marital_status_display }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'place_of_birth' }}:
                </span>
                    {{ patient.place_of_birth }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'gender' }}:
                </span>
                    {{ patient.get_gender_display|default_if_none:'' }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'phone' }}:
                </span>
                    {{ patient.phone }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5 class="card-title">
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'observation' }}:
                </span>
                    {{ patient.observation }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'created_by' }}:
                </span>
                    {{ patient.created_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'created_at' }}:
                </span>
                    {{ patient.created_at|date:"d/m/Y" }} {{ patient.created_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'updated_by' }}:
                </span>
                    {{ patient.updated_by|default_if_none:"" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'updated_at' }}:
                </span>
                    {{ patient.updated_at|date:"d/m/Y" }} {{ patient.updated_at|time:"H:i:s" }}
                </h5>
            </div>
            <div class="row mb-3">
                <h5>
                <span class="font-weight-bold">
                    {{ patient|get_verbose_name:'is_active' }}:
                </span>
                    {% if patient.is_active %}
                        {% include 'utils/icons/icon_check_circle.html' %}
                    {% else %}
                        {% include 'utils/icons/icon_times_circle.html' %}
                    {% endif %}
                </h5>
            </div>
        </div>
    </div>
    <div class="my-4 text-center">
        <a href="{% url 'medicine:patient-list' %}">
            {% include 'utils/forms/form_back_btn.html' %}
        </a>
    </div>
{% endblock content %}