medicine/urls.py
from django.urls import path

from .views.medical_evaluation_views import (MedicalEvaluationListView,
                                             create_medical_evaluation,
                                             deactivate_medical_evaluation,
                                             list_medical_evaluations,
                                             medical_evaluation_detail,
                                             update_medical_evaluation)
from .views.medication_views import (MedicationListView, create_medication,
                                     deactivate_medication, list_medications,
                                     medication_detail, update_medication)
from .views.medicine_views import (MedicineListView, create_medicine,
                                   deactivate_medicine, list_medicines,
                                   medicine_detail, update_medicine)
from .views.nursing_professional_views import (
    NursingProfessionalAutocompleteView, NursingProfessionalListView,
    create_nursing_professional, deactivate_nursing_professional,
    list_nursing_professionals, nursing_professional_detail,
    update_nursing_professional)
from .views.patient_views import (PatientAutocompleteView, PatientListView,
                                  create_patient, deactivate_patient,
                                  list_patients, patient_detail,
                                  update_patient)

app_name = 'medicine'

prefix_medicine_url = 'medicine'
prefix_patient_url = 'patient'
prefix_nursing_professional_url = 'nursing-professional'
prefix_medical_evaluation_url = 'medical-evaluation'
prefix_medication_url = 'medication'

urlpatterns = [
    # Medicine
    path(
        route=f'{prefix_medicine_url}/list/',
        view=list_medicines,
        name='medicine-list'
    ),
    path(
        route=f'{prefix_medicine_url}/detail/<int:pk>/',
        view=medicine_detail,
        name='medicine-detail'
    ),
    path(
        route=f'{prefix_medicine_url}/create/',
        view=create_medicine,
        name='medicine-create'
    ),
    path(
        route=f'{prefix_medicine_url}/update/<int:pk>/',
        view=update_medicine,
        name='medicine-update'
    ),
    path(
        route=f'{prefix_medicine_url}/deactivate/<int:pk>/',
        view=deactivate_medicine,
        name='medicine-deactivate'
    ),
    path(
        route=f'{prefix_medicine_url}/data/',
        view=MedicineListView.as_view(),
        name='medicine-data'
    ),

    # Patient
    path(
        route=f'{prefix_patient_url}/list/',
        view=list_patients,
        name='patient-list'),
    path(
        route=f'{prefix_patient_url}/detail/<int:pk>/',
        view=patient_detail,
        name='patient-detail'),
    path(
        route=f'{prefix_patient_url}/create/',
        view=create_patient,
        name='patient-create'),
    path(
        route=f'{prefix_patient_url}/update/<int:pk>/',
        view=update_patient,
        name='patient-update'),
    path(
        route=f'{prefix_patient_url}/deactivate/<int:pk>/',
        view=deactivate_patient,
        name='patient-deactivate'
    ),
    path(
        route=f'{prefix_patient_url}/data/',
        view=PatientListView.as_view(),
        name='patient-data'
    ),
    path(
        route=f'{prefix_patient_url}/autocomplete/',
        view=PatientAutocompleteView.as_view(),
        name='patient-autocomplete'
    ),

    # Nursing Professional
    path(
        route=f'{prefix_nursing_professional_url}/list/',
        view=list_nursing_professionals,
        name='nursing-professional-list'),
    path(
        route=f'{prefix_nursing_professional_url}/detail/<int:pk>/',
        view=nursing_professional_detail,
        name='nursing-professional-detail'),
    path(
        route=f'{prefix_nursing_professional_url}/create/',
        view=create_nursing_professional,
        name='nursing-professional-create'),
    path(
        route=f'{prefix_nursing_professional_url}/update/<int:pk>/',
        view=update_nursing_professional,
        name='nursing-professional-update'),
    path(
        route=f'{prefix_nursing_professional_url}/deactivate/<int:pk>/',
        view=deactivate_nursing_professional,
        name='nursing-professional-deactivate'
    ),
    path(
        route=f'{prefix_nursing_professional_url}/data/',
        view=NursingProfessionalListView.as_view(),
        name='nursing-professional-data'
    ),
    path(
        route=f'{prefix_nursing_professional_url}/autocomplete/',
        view=NursingProfessionalAutocompleteView.as_view(),
        name='nursing-professional-autocomplete'
    ),

    # Medical Evaluation
    path(
        route=f'{prefix_medical_evaluation_url}/list/',
        view=list_medical_evaluations,
        name='medical-evaluation-list'),
    path(
        route=f'{prefix_medical_evaluation_url}/detail/<int:pk>/',
        view=medical_evaluation_detail,
        name='medical-evaluation-detail'),
    path(
        route=f'{prefix_medical_evaluation_url}/create/',
        view=create_medical_evaluation,
        name='medical-evaluation-create'),
    path(
        route=f'{prefix_medical_evaluation_url}/update/<int:pk>/',
        view=update_medical_evaluation,
        name='medical-evaluation-update'),
    path(
        route=f'{prefix_medical_evaluation_url}/deactivate/<int:pk>/',
        view=deactivate_medical_evaluation,
        name='medical-evaluation-deactivate'
    ),
    path(
        route=f'{prefix_medical_evaluation_url}/data/',
        view=MedicalEvaluationListView.as_view(),
        name='medical-evaluation-data'
    ),

    # Medication
    path(
        route=f'{prefix_medication_url}/list/',
        view=list_medications,
        name='medication-list'),
    path(
        route=f'{prefix_medication_url}/detail/<int:pk>/',
        view=medication_detail,
        name='medication-detail'),
    path(
        route=f'{prefix_medication_url}/create/',
        view=create_medication,
        name='medication-create'),
    path(
        route=f'{prefix_medication_url}/update/<int:pk>/',
        view=update_medication,
        name='medication-update'),
    path(
        route=f'{prefix_medication_url}/deactivate/<int:pk>/',
        view=deactivate_medication,
        name='medication-deactivate'
    ),
    path(
        route=f'{prefix_medication_url}/data/',
        view=MedicationListView.as_view(),
        name='medication-data'
    ),
]

senioren/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog
from medicine.views.index_views import index
from user.views import login, logout

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),

    path('', index, name='index'),

    path('admin/', admin.site.urls, name='admin'),

    path('medicines/', include('medicine.urls', namespace='medicine')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="Senioren - Sistema de Administração de Medicamentos"/>
    <meta name="author" content="Stévillis Monteiro de Sousa"/>

    <title>
        {% block title %}

        {% endblock title %}
    </title>

    <!-- favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'img/brand/favicon.ico' %}"/>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"/>
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet"/>

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet"/>

    <!-- Datatables -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

    {% block custom_css %}

    {% endblock custom_css %}
</head>

<body id="page-top">
<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
            <div class="sidebar-brand-icon">
                <img src="{% static 'img/brand/apple-touch-icon.png' %}" alt="Senioren brand" width="64"
                     height="64"/>
            </div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0"/>

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">
                <i class="fas fa-fw fa-house-user"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider"/>

        <!-- Heading -->
        <div class="sidebar-heading">Cadastros</div>

        <!-- Nav Item - Medicações -->
        <li class="nav-item text-center">
            <a class="nav-link collapsed" href="{% url 'medicine:medication-list' %}">
                <i class="fas fa-fw fa-file-medical"></i>
                <span>Medicações</span>
            </a>
        </li>

        <!-- Nav Item - Medical Evaluations -->
        <li class="nav-item text-center">
            <a class="nav-link collapsed" href="{% url 'medicine:medical-evaluation-list' %}">
                <i class="fas fa-fw fa-clinic-medical"></i>
                <span>Avaliações Médicas</span>
            </a>
        </li>

        <!-- Nav Item - Medicines -->
        <li class="nav-item text-center">
            <a class="nav-link collapsed" href="{% url 'medicine:medicine-list' %}">
                <i class="fas fa-fw fa-pills"></i>
                <span>Medicamentos</span>
            </a>
        </li>

        <!-- Nav Item - Patients -->
        <li class="nav-item text-center">
            <a class="nav-link collapsed" href="{% url 'medicine:patient-list' %}">
                <i class="fas fa-fw fa-hospital-user"></i>
                <span>Pacientes</span>
            </a>
        </li>

        <!-- Nav Item - Nursing Professionals -->
        <li class="nav-item text-center">
            <a class="nav-link collapsed" href="{% url 'medicine:nursing-professional-list' %}">
                <i class="fas fa-fw fa-user-nurse"></i>
                <span>Profissionais de Enfermagem</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block"/>

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Navbar -->
                {% if user.is_superuser %}
                    <ul class="d-flex align-items-center navbar-nav ml-auto">
                        <!-- Nav Item - Messages -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a href="{% url 'admin:index' %}"
                               class="d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                                Admin
                            </a>
                        </li>
                        <li class="nav-item no-arrow ml-3 mr-1">
                            <a href="{% url 'logout' %}" class="text-danger">
                                <i class="fas fa-fw fa-sign-out-alt"></i>
                            </a>
                        </li>
                    </ul>
                {% endif %}
            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">
                        {% block content_title %} {% endblock content_title %}
                    </h1>
                </div>

                {% block content %} {% endblock content %}
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Senioren - desenvolvido por Stévillis Sousa, 2022</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

<!-- Datatables -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>


<!-- Internationalization: in JavaScript code -->
<script src="{% url 'javascript-catalog' %}"></script>

<!-- jQuery Mask Plugin -->
<script src="{% static 'vendor/jQueryMaskPlugin/jquery.mask.min.js' %}"></script>

{% block custom_script %}

{% endblock custom_script %}
</body>

</html>

templates/login.html
{% load static %}

{% load custom_tags %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content="Stévillis Monteiro de Sousa"/>

    <title>Senioren - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet"/>

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet"/>
</head>

<body class="bg-gradient-primary">
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row justify-content-center">
                        <div class="col-lg-8">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h1 text-gray-900 mb-4">Senioren</h1>
                                </div>
                                <form method="post" action="{% url 'login' %}" class="user" autocomplete="off">
                                    {% csrf_token %}

                                    <div class="form-group">
                                        {% if form.email.errors %}
                                            {{ form.email|add_class:'form-control form-control-user is-invalid' }}
                                            <small class="text-danger">
                                                {{ form.email.errors|striptags }}
                                            </small>
                                        {% else %}
                                            {{ form.email|add_class:'form-control form-control-user' }}
                                        {% endif %}
                                    </div>
                                    <div class="form-group">
                                        {% if form.password.errors %}
                                            {{ form.password|add_class:'form-control form-control-user is-invalid' }}
                                            <small class="text-danger">{{ form.password.errors|striptags }}</small>
                                        {% else %}
                                            {{ form.password|add_class:'form-control form-control-user' }}
                                        {% endif %}
                                    </div>

                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        Login
                                    </button>
                                </form>
                                <hr/>
                                <div class="text-center">
                                    <a class="small" href="{% url 'admin:index' %}">Admin</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>

</html>